import { defineAdventureScenario, reviewAdventureScenario } from "./adventure";

export const EP1_ADVENTURE = defineAdventureScenario({
  id: "ep1-case-unconscious-response",
  caseNo: "CASE 01",
  title: "動かなかった足は、なぜ動いた？",
  question: "命令では動かなかった足に、何が最初の反応を起こした？",
  objective: "3つの証拠から、足に小さな反応が起きた条件を特定する",
  background: "/learn/adventure/erickson-study-v1.webp",
  teacherSprite: "/learn/adventure/erickson-cutout-v1.webp",
  linkSprite: "/learn/chars/link-neutral.webp",
  evidence: [
    {
      id: "direct-command",
      title: "届かなかった命令",
      summary: "足へ「動け」と命令 → 反応なし",
      detail: "力を込めて足へ直接命令しても、足には確認できる反応が起きなかった。",
      icon: "✕",
    },
    {
      id: "vivid-image",
      title: "走る身体感覚",
      summary: "外を走る感覚へ注意 → 足に小さな反応",
      detail: "足への命令をやめ、外で走っていた頃の感覚へ注意が向いたとき、足に小さな反応が起きた。",
      icon: "◉",
    },
    {
      id: "observation-loop",
      title: "反応の確認と反復",
      summary: "椅子の揺れで足の反応を確認し、再現した",
      detail: "椅子の揺れは目的ではなく、足の小さな反応を外から確認できた証拠。その後、歩行を観察して反応を育てた。",
      icon: "↻",
    },
  ],
  nodes: [
    {
      kind: "dialogue",
      id: "adv-01",
      scene: "事件発生",
      camera: "link",
      line: { id: "adv-01", who: "link", face: "think", text: "先生、確認です。調べるのは、椅子を動かした条件ではなく、動かなかった足に反応が出た条件ですよね？" },
      nextLabel: "何を調べるか確かめる",
    },
    {
      kind: "dialogue",
      id: "adv-02",
      scene: "事件発生",
      camera: "teacher",
      line: { id: "adv-02", who: "teacher", face: "smile", text: "その通りです。椅子の揺れは、足の反応が外から見えた証拠です。椅子を動かすことが目的ではありません。" },
    },
    {
      kind: "dialogue",
      id: "adv-03",
      scene: "事件発生",
      camera: "link",
      line: { id: "adv-03", who: "link", face: "aha", text: "命令しても動かなかった足が、いつ、何をきっかけに反応したのか。起きた順番を追います。" },
      nextLabel: "足の反応を調べる",
    },
    {
      kind: "investigate",
      id: "investigate-room",
      scene: "現場検証",
      title: "足に反応が起きた順番を調べろ",
      prompt: "光っている3か所をタップし、命令・最初の反応・その後の行動を集めてください。",
      spots: [
        { id: "spot-chair", label: "足元と揺り椅子", x: 32, y: 57, evidenceId: "direct-command", linkComment: "ここが出発点。足へ命令しても、反応は起きなかった。" },
        { id: "spot-window", label: "窓の外", x: 49, y: 29, evidenceId: "vivid-image", linkComment: "外を走る感覚へ注意が向いた。そのとき初めて、足に小さな反応が出た。" },
        { id: "spot-board", label: "観察記録", x: 84, y: 43, evidenceId: "observation-loop", linkComment: "椅子の揺れで反応に気づき、その後も歩き方を観察して繰り返した。" },
      ],
    },
    {
      kind: "dialogue",
      id: "adv-04",
      scene: "仮説",
      camera: "link",
      line: { id: "adv-04", who: "link", face: "think", text: "足への命令では反応なし。走る感覚へ注意が向くと小さな反応。その後に確認と反復……順番が見えました。" },
    },
    {
      kind: "dialogue",
      id: "adv-05",
      scene: "仮説",
      camera: "teacher",
      line: { id: "adv-05", who: "teacher", text: "ではリンク。動かなかった足に、最初の反応を起こした条件を選んでください。" },
      nextLabel: "仮説を選ぶ",
    },
    {
      kind: "deduction",
      id: "deduce-trigger",
      scene: "推理",
      title: "足に最初の反応を起こした条件は？",
      prompt: "命令したときと、その後に足が反応したときを比べてください。",
      hint: "足が動かなかった場面と、小さく反応した場面の違いを見る。",
      options: [
        { id: "willpower", label: "足へ『動け』と強く命令したこと", correct: false, feedback: "その場面では足は反応しませんでした。最初の証拠と矛盾します。" },
        { id: "imagery", label: "外を走る身体感覚へ注意が向いたこと", correct: true, feedback: "正解。足への命令をやめ、走る感覚へ注意が向いたときに最初の反応が起きました。" },
        { id: "chair", label: "揺り椅子に座っていたこと", correct: false, feedback: "椅子は足の反応を確認できた証拠です。反応を起こした条件そのものではありません。" },
      ],
    },
    {
      kind: "reveal",
      id: "reveal-trigger",
      scene: "推理成立",
      kicker: "HYPOTHESIS CONFIRMED",
      title: "足への命令をやめ、走る感覚へ注意が向いた",
      body: "動かなかった足に最初の反応が起きたのは、外を走る身体感覚へ注意が向いたとき。椅子の揺れは、その反応を確認できた結果です。",
      evidenceIds: ["direct-command", "vivid-image", "observation-loop"],
      nextLabel: "その後の行動を確かめる",
    },
    {
      kind: "dialogue",
      id: "adv-06",
      scene: "意味の確認",
      camera: "link",
      line: { id: "adv-06", who: "link", face: "think", text: "でも、走る感覚を思い出しただけで、急に歩けるようになったわけではないですよね？" },
    },
    {
      kind: "dialogue",
      id: "adv-07",
      scene: "意味の確認",
      camera: "teacher",
      line: { id: "adv-07", who: "teacher", face: "smile", text: "ええ。最初は小さな反応です。それを偶然で終わらせず、観察し、再現し、少しずつ広げました。" },
      nextLabel: "その後の行動を選ぶ",
    },
    {
      kind: "deduction",
      id: "deduce-hypnosis",
      scene: "推理",
      title: "小さな反応を、変化の材料にした行動は？",
      prompt: "最初の反応が起きたあと、エリクソンが続けたことを選んでください。",
      options: [
        { id: "use-command", label: "もう一度、足へ強く命令した", correct: false, feedback: "最初に失敗した方法へ戻っています。証拠では、命令ではなく観察を続けました。" },
        { id: "use-loop", label: "足の反応を確認し、歩き方を観察して反復した", correct: true, feedback: "正解。小さな反応を確認し、再現できる条件として少しずつ育てました。" },
        { id: "use-wait", label: "次の奇跡が起きるまで何もしなかった", correct: false, feedback: "観察記録と矛盾します。エリクソンは妹の歩き方を観察し、反応を繰り返しました。" },
      ],
    },
    {
      kind: "reveal",
      id: "reveal-hypnosis",
      scene: "因果成立",
      kicker: "CAUSAL CHAIN COMPLETE",
      title: "見つけた反応を、観察・再現・拡大した",
      body: "足に起きた小さな反応を見つけ、椅子の揺れで確認し、歩行の観察と反復で広げた。回復は一瞬の魔法ではありません。",
      evidenceIds: ["vivid-image", "observation-loop"],
      nextLabel: "自分のテーマへ使う",
    },
    {
      kind: "dialogue",
      id: "adv-08",
      scene: "自分への適用",
      camera: "link",
      line: { id: "adv-08", who: "link", face: "aha", dynamic: true, text: "事件と同じ見方なら、『{{theme}}』も『{{exception}}』では{{exceptionScore}}だった。その差を調べるんですね。" },
    },
    {
      kind: "dialogue",
      id: "adv-09",
      scene: "自分への適用",
      camera: "teacher",
      line: { id: "adv-09", who: "teacher", dynamic: true, text: "ええ。100から{{exceptionScore}}へ変わった時にあった『{{clue}}』が、最初に確かめる条件です。" },
      nextLabel: "自分の一手を決める",
    },
    {
      kind: "apply",
      id: "apply-self",
      scene: "適用",
      title: "あなたの最初の一手",
      prompt: "『{{theme}}』を100から{{exceptionScore}}へ動かした条件を、次にどう使いますか？",
      storeAs: "resource",
      options: [
        { id: "push", label: "できるまで自分へ強く命令する", value: "命令を強める", correct: false, feedback: "漫画で失敗した方法と同じです。力を増やす前に、反応の条件を探します。" },
        { id: "analyze", label: "100だった原因を全部分析する", value: "100だった原因を全部分析する", correct: false, feedback: "原因探しだけでは、100ではなかった瞬間に実際に起きた差を見落とします。" },
        { id: "observe", label: "『{{clue}}』を次の場面で一つ再現する", value: "{{clue}}を次の場面で一つ再現する", correct: true, feedback: "正解。100との差を実際に作った条件を、小さく試す一手です。" },
      ],
    },
    {
      kind: "dialogue",
      id: "adv-10",
      scene: "解決",
      camera: "link",
      line: { id: "adv-10", who: "link", face: "smile", dynamic: true, text: "『{{theme}}』をゼロにするんじゃない。まず『{{resource}}』。これなら試せそうです。" },
    },
    {
      kind: "dialogue",
      id: "adv-11",
      scene: "解決",
      camera: "teacher",
      line: { id: "adv-11", who: "teacher", face: "smile", dynamic: true, text: "次の機会に『{{resource}}』。結果が99でも、100ではない反応が起きたなら観察は成功です。" },
    },
    {
      kind: "dialogue",
      id: "adv-12",
      scene: "解決",
      camera: "link",
      line: { id: "adv-12", who: "link", face: "aha", text: "足の反応を見つけたのと同じように、問題を消す前に100ではない実例を調べる。話がつながりました。" },
      nextLabel: "事件の答えを確定する",
    },
    {
      kind: "reveal",
      id: "case-closed",
      scene: "CASE CLOSED",
      kicker: "CASE CLOSED",
      title: "命令する前に、起きた反応を見つける",
      body: "動かなかった足には、走る身体感覚へ注意が向いたとき、小さな反応が起きた。その反応を観察し、再現し、広げたことが事件の答えです。",
      evidenceIds: ["direct-command", "vivid-image", "observation-loop"],
      nextLabel: "講義で理屈を確かめる",
    },
  ],
});

/** 開発画面・自動生成パイプラインから読める審査結果 */
export const EP1_ADVENTURE_QUALITY = reviewAdventureScenario(EP1_ADVENTURE);
