import { defineAdventureScenario, reviewAdventureScenario } from "./adventure";

export const EP1_ADVENTURE = defineAdventureScenario({
  id: "ep1-case-hypnosis-entry",
  caseNo: "CASE 01",
  title: "動かなかった足が動いた時、エリクソンは何をした？",
  objective: "漫画の場面を証拠として開き、足が動いた後の行動を選ぶ",
  background: "/learn/adventure/erickson-study-v1.webp",
  teacherSprite: "/learn/adventure/erickson-cutout-v1.webp",
  linkSprite: "/learn/chars/link-neutral.webp",
  evidence: [
    {
      id: "command",
      title: "動けと命じた時",
      summary: "エリクソンは身体へ『動け』と強く命じた",
      detail: "本人は強く動きたいと思っていたが、この時、身体も揺り椅子も動かなかった。",
      icon: "✕",
      image: "/learn/ep1/manga-v2/02.webp",
      imageAlt: "動けと強く念じても、足も揺り椅子も動かなかった漫画場面",
    },
    {
      id: "running-memory",
      title: "走る自分を思い出した時",
      summary: "足の裏、土、風など、走っていた時の感じを思い出した",
      detail: "その時、身体にごく小さな動きが起こり、揺り椅子がわずかに動いた。どの筋肉が原因かは、この逸話だけでは決めない。",
      icon: "↻",
      image: "/learn/ep1/manga-v2/03-v3.webp",
      imageAlt: "走っていた時の感覚を思い出すと、足が反応して揺り椅子が動いた漫画場面",
    },
    {
      id: "sister-walking",
      title: "妹が歩く様子",
      summary: "妹の一歩を、かかと、体重の移動、つま先に分けて見た",
      detail: "一歩を丸ごと真似ようとせず、小さな動きとして見て、自分の身体で確かめた。",
      icon: "◉",
      image: "/learn/ep1/manga-v2/04-v4.png",
      imageAlt: "妹の歩き方を観察し、自分の足で小さな動きを確かめる漫画場面",
    },
    {
      id: "long-training",
      title: "長い訓練の記録",
      summary: "一度のイメージで治ったのではなく、小さな動きを長い時間かけて広げた",
      detail: "イメージだけでポリオが治ったという話ではない。起きた動きを何度も確かめ、できる動きを少しずつ広げた。",
      icon: "①",
      image: "/learn/ep1/manga-v2/05-v3.webp",
      imageAlt: "長い時間をかけて動きを広げ、杖で歩くエリクソンの漫画場面",
    },
  ],
  nodes: [
    {
      kind: "dialogue",
      id: "adv-01",
      scene: "足の事件へ戻る",
      camera: "link",
      line: { id: "adv-01", who: "link", face: "think", text: "先生。これは身体の訓練の話ですよね。催眠の授業と、どこでつながるんですか？" },
      nextLabel: "漫画へ戻る",
    },
    {
      kind: "dialogue",
      id: "adv-02",
      scene: "足の事件へ戻る",
      camera: "teacher",
      line: { id: "adv-02", who: "teacher", text: "{{userName}}。まず漫画の三場面を証拠として開き、足が動いた後に私が何をしたかを確かめてください。", dynamic: true },
      nextLabel: "証拠を開く",
    },
    {
      kind: "investigate",
      id: "investigate-three-scenes",
      scene: "三場面を確認",
      title: "動かなかった足が動いた後、何をした？",
      prompt: "命令した時、足が反応した時、妹の歩き方を見た時の漫画を開いてください。",
      spots: [
        { id: "spot-command", label: "動けと命じた時", x: 24, y: 59, evidenceId: "command", linkComment: "動きたい気持ちは強い。でも、この場面では身体も椅子も動いていない。" },
        { id: "spot-memory", label: "足が反応した時", x: 53, y: 48, evidenceId: "running-memory", linkComment: "走る感覚を思い出した時、足が反応し、身体が椅子をわずかに揺らした。" },
        { id: "spot-sister", label: "妹が歩いた時", x: 82, y: 59, evidenceId: "sister-walking", linkComment: "妹の一歩を小さな動きへ分け、自分の身体で確かめている。" },
      ],
    },
    {
      kind: "dialogue",
      id: "adv-03",
      scene: "最初の推理",
      camera: "link",
      line: { id: "adv-03", who: "link", face: "think", text: "『動け』と念じた時は動かない。走る感覚を思い出した時に足が反応し、その後は妹の歩き方を見ている。" },
    },
    {
      kind: "dialogue",
      id: "adv-04",
      scene: "最初の推理",
      camera: "teacher",
      line: { id: "adv-04", who: "teacher", text: "この漫画から、足が動いた後に私が選んだ行動を一つ決めてください。" },
      nextLabel: "行動を選ぶ",
    },
    {
      kind: "deduction",
      id: "deduce-foot-story",
      scene: "第一推理",
      title: "足が動いた後、エリクソンは何をした？",
      prompt: "漫画の証拠に合う行動を一つ選んでください。",
      options: [
        { id: "cure", label: "走る場面をイメージすれば、麻痺した身体は治る", correct: false, feedback: "長い訓練の記録と合いません。一度のイメージで治ったとは書かれていません。" },
        { id: "use-movement", label: "足に起きたわずかな動きを、もう一度起こし、少しずつ大きくできないか試した", correct: true, feedback: "正解です。足が実際に動いた瞬間を手がかりに、その動きを反復して広げようとしました。" },
        { id: "chair", label: "揺り椅子から受けた刺激が、足を治した", correct: false, feedback: "漫画では身体の小さな動きが先です。椅子が身体を治した記録ではありません。" },
      ],
    },
    {
      kind: "reveal",
      id: "reveal-foot-story",
      scene: "第一推理成立",
      kicker: "WHAT HE USED",
      title: "足に起きた小さな動きを、反復して広げた",
      body: "椅子の揺れで、足に動きが起きたと気づいた。そこで『動け』と念じるだけをやめ、走った感覚や家族の動きを手がかりに、その小さな動きを何度も確かめた。",
      evidenceIds: ["command", "running-memory", "sister-walking", "long-training"],
      nextLabel: "催眠との関係へ",
    },
    {
      kind: "dialogue",
      id: "adv-05",
      scene: "催眠との関係",
      camera: "link",
      line: { id: "adv-05", who: "link", face: "think", text: "足の動きを反復して広げたことは分かりました。でも、それが催眠のかけ方とどうつながるんです？" },
      nextLabel: "二つを比べる",
    },
    {
      kind: "dialogue",
      id: "adv-06",
      scene: "催眠との関係",
      camera: "teacher",
      line: { id: "adv-06", who: "teacher", text: "私が足にしたことと、{{userName}}がリンクにしたこと。二つに共通する行動を選んでください。", dynamic: true },
      nextLabel: "共通点を選ぶ",
    },
    {
      kind: "deduction",
      id: "deduce-hypnosis-link",
      scene: "第二推理",
      title: "足の出来事と、リンクへの催眠に共通することは？",
      prompt: "できなかった指示と、本人に実際に起きた反応をどう扱ったでしょう。",
      options: [
        { id: "repeat", label: "できるまで、同じ指示を強く繰り返した", correct: false, feedback: "反対です。足へも、海辺の様子が浮かばない人へも、同じ指示を押し続けていません。" },
        { id: "fit", label: "できない指示を繰り返さず、実際に起きた反応を見つけ、もう一度起こせるか確かめた", correct: true, feedback: "正解です。足では実際に動いた瞬間を反復し、リンクには実際に感じられるものから催眠を始めました。" },
        { id: "pretend", label: "できなくても、できたことにして先へ進めた", correct: false, feedback: "分からないまま、催眠に入ったことにはしていません。実際にできたことだけを使います。" },
      ],
    },
    {
      kind: "reveal",
      id: "reveal-utilization",
      scene: "事件解決",
      kicker: "ERICKSON PRINCIPLE 01",
      title: "足なら動いた瞬間、リンクなら感じられたものを使う",
      body: "足では、実際に動いた瞬間を反復した。リンクには、言葉、身体感覚、今見えているものから注意を集めるきっかけを作った。本人にすでに起きている反応を次へ使う考え方を、Utilizationと呼ぶ。",
      evidenceIds: ["running-memory", "sister-walking"],
      nextLabel: "日常の場面で試す",
    },
    {
      kind: "dialogue",
      id: "adv-daily-01",
      scene: "日常で使う",
      camera: "link",
      line: { id: "adv-daily-01", who: "link", face: "think", text: "正式な催眠だけではなく、日常ではどんな場面で使えるんです？" },
      nextLabel: "日常の場面を見る",
    },
    {
      kind: "dialogue",
      id: "adv-daily-02",
      scene: "日常で使う",
      camera: "teacher",
      line: { id: "adv-daily-02", who: "teacher", text: "友人が催眠の練習に同意しました。しかし緊張して、落ち着く場所をイメージできません。最初の一言を選んでください。" },
      nextLabel: "最初の一言を選ぶ",
    },
    {
      kind: "apply",
      id: "apply-daily-utilization",
      scene: "日常の短い催眠",
      title: "緊張している友人へ、最初に何と言う？",
      prompt: "友人は椅子に座り、催眠の練習を始めることに同意しています。",
      storeAs: "dailyStep",
      options: [
        { id: "relax", label: "『力を抜いて、もっとリラックスして』と繰り返す", correct: false, value: "同じ指示を繰り返した", feedback: "『リラックスできない』という今の状態を無視しています。できない指示を強くしても、催眠は進みません。" },
        { id: "feet", label: "『今、両足が床に触れている感じは分かりますか？』と聞く", correct: true, value: "足が床に触れている感覚から、注意を集めるきっかけを作った", feedback: "正解です。本人が今実際に感じられる足裏の感覚から、短い催眠を始められます。" },
        { id: "beach", label: "落ち着く海辺を、もっとはっきりイメージしてもらう", correct: false, value: "同じイメージを求めた", feedback: "友人ができないと言った方法を繰り返しています。別の感覚から始める必要があります。" },
      ],
    },
    {
      kind: "dialogue",
      id: "adv-07",
      scene: "事件解決",
      camera: "link",
      line: { id: "adv-07", who: "link", face: "aha", text: "できないイメージを押しつけず、今感じられるものから催眠を始める。これなら日常の場面でも分かります。" },
    },
    {
      kind: "dialogue",
      id: "adv-08",
      scene: "事件解決",
      camera: "teacher",
      line: { id: "adv-08", who: "teacher", face: "smile", text: "{{userName}}。今の判断で第1の事件は解決です。講義で、催眠、暗示、Utilizationの順に整理します。", dynamic: true },
      nextLabel: "講義へ進む",
    },
  ],
});

export const EP1_ADVENTURE_QUALITY = reviewAdventureScenario(EP1_ADVENTURE);
