import { defineAdventureScenario, reviewAdventureScenario } from "./adventure";

export const EP1_ADVENTURE = defineAdventureScenario({
  id: "ep1-case-unconscious-response",
  caseNo: "CASE 01",
  title: "動いたのは、誰の命令か",
  question: "命令をやめた瞬間、なぜ椅子は動いた？",
  objective: "3つの証拠を集め、無意識が反応した条件を特定する",
  background: "/learn/adventure/erickson-study-v1.webp",
  teacherSprite: "/learn/adventure/erickson-cutout-v1.webp",
  linkSprite: "/learn/chars/link-neutral.webp",
  evidence: [
    {
      id: "direct-command",
      title: "届かなかった命令",
      summary: "「脚を動かせ」→反応なし",
      detail: "力を込めた直接命令では、脚も揺り椅子も動かなかった。",
      icon: "✕",
    },
    {
      id: "vivid-image",
      title: "走るイメージ",
      summary: "命令をやめた直後に椅子が動いた",
      detail: "外を走る感覚へ注意が向いたとき、本人が意図しない小さな身体反応が起きた。",
      icon: "◉",
    },
    {
      id: "observation-loop",
      title: "観察と反復",
      summary: "妹の歩行を分解して何度も観察",
      detail: "一度の奇跡ではなく、かかと・重心・つま先を観察し、小さな反応を二年間育てた。",
      icon: "↻",
    },
  ],
  nodes: [
    {
      kind: "dialogue",
      id: "adv-01",
      scene: "事件発生",
      camera: "link",
      line: { id: "adv-01", who: "link", face: "think", text: "先生。命令をやめたら椅子が動くって……それ、ただの偶然じゃないんですか？" },
      nextLabel: "エリクソンの答えを聞く",
    },
    {
      kind: "dialogue",
      id: "adv-02",
      scene: "事件発生",
      camera: "teacher",
      line: { id: "adv-02", who: "teacher", face: "smile", text: "よい疑いです。私の説明を信じる必要はありません。起きた順番を調べてみましょう。" },
    },
    {
      kind: "dialogue",
      id: "adv-03",
      scene: "事件発生",
      camera: "link",
      line: { id: "adv-03", who: "link", face: "aha", text: "講義を聞く前に、証拠を集めるってことですね。いいですよ。僕が見つけます。" },
      nextLabel: "部屋を調べる",
    },
    {
      kind: "investigate",
      id: "investigate-room",
      scene: "現場検証",
      title: "反応が起きた部屋を調べろ",
      prompt: "光っている3か所をタップして、起きた順番を集めてください。",
      spots: [
        { id: "spot-chair", label: "揺り椅子", x: 32, y: 57, evidenceId: "direct-command", linkComment: "最初は、どれだけ命令しても動かなかったんだ。" },
        { id: "spot-window", label: "窓の外", x: 49, y: 29, evidenceId: "vivid-image", linkComment: "窓を見て、外を走る感覚を思い出した。その直後に……。" },
        { id: "spot-board", label: "観察記録", x: 84, y: 43, evidenceId: "observation-loop", linkComment: "椅子が動いた後も、妹の足を見て二年も試し続けてる。" },
      ],
    },
    {
      kind: "dialogue",
      id: "adv-04",
      scene: "仮説",
      camera: "link",
      line: { id: "adv-04", who: "link", face: "think", text: "命令は失敗。走るイメージの直後に反応。その後は観察と反復……順番に意味がありそうです。" },
    },
    {
      kind: "dialogue",
      id: "adv-05",
      scene: "仮説",
      camera: "teacher",
      line: { id: "adv-05", who: "teacher", text: "ではリンク。椅子を動かした条件を、三つの仮説から選んでください。" },
      nextLabel: "仮説を選ぶ",
    },
    {
      kind: "deduction",
      id: "deduce-trigger",
      scene: "推理",
      title: "椅子を動かした条件は？",
      prompt: "3つの証拠と矛盾しない仮説を選んでください。",
      hint: "命令したときと、命令をやめた後を比べる。",
      options: [
        { id: "willpower", label: "動かそうとする意志が強くなった", correct: false, feedback: "でも強く命令したときは動かなかった。最初の証拠と矛盾します。" },
        { id: "chance", label: "回復が偶然その瞬間に始まった", correct: false, feedback: "一度だけならあり得る。でも同じイメージで反応を再現しています。" },
        { id: "imagery", label: "走るイメージが無意識の反応を起こした", correct: true, feedback: "証拠が一本につながりました。命令ではなく、注意とイメージが条件です。" },
      ],
    },
    {
      kind: "reveal",
      id: "reveal-trigger",
      scene: "推理成立",
      kicker: "HYPOTHESIS CONFIRMED",
      title: "命令ではなく、反応の条件をつくった",
      body: "外を走る感覚へ注意が向いたとき、身体は小さく反応した。エリクソンはその反応を見つけ、再現し、広げた。",
      evidenceIds: ["direct-command", "vivid-image", "observation-loop"],
      nextLabel: "もう一つの誤解へ",
    },
    {
      kind: "dialogue",
      id: "adv-06",
      scene: "反論",
      camera: "link",
      line: { id: "adv-06", who: "link", face: "aha", text: "あれ？　これって誰かに操られたんじゃなく、自分の中の反応を自分で見つけた話ですよね。" },
    },
    {
      kind: "dialogue",
      id: "adv-07",
      scene: "反論",
      camera: "teacher",
      line: { id: "adv-07", who: "teacher", face: "smile", text: "その通り。では『催眠は命令で人を操るものだ』という思い込みを、証拠で崩してください。" },
      nextLabel: "証拠を突きつける",
    },
    {
      kind: "deduction",
      id: "deduce-hypnosis",
      scene: "証拠提示",
      title: "思い込みと矛盾する証拠は？",
      prompt: "『催眠は命令で操るもの』を最も直接否定する証拠を選んでください。",
      options: [
        { id: "use-command", label: "届かなかった命令", correct: true, feedback: "正解。直接命令は失敗し、命令をやめた後に反応が起きています。" },
        { id: "use-image", label: "走るイメージ", correct: false, feedback: "重要な証拠ですが、『命令で操る』を直接否定するなら失敗した命令です。" },
        { id: "use-loop", label: "観察と反復", correct: false, feedback: "回復が一瞬の魔法ではない証拠です。今回は命令との矛盾を探します。" },
      ],
    },
    {
      kind: "reveal",
      id: "reveal-hypnosis",
      scene: "誤解解除",
      kicker: "MISCONCEPTION BROKEN",
      title: "催眠は「支配」ではなく「注意の使い方」",
      body: "相手を力で動かすのではなく、その人の中ですでに起きる注意・イメージ・身体反応を利用する。",
      evidenceIds: ["direct-command", "vivid-image"],
      nextLabel: "自分のテーマへ使う",
    },
    {
      kind: "dialogue",
      id: "adv-08",
      scene: "自分への適用",
      camera: "link",
      line: { id: "adv-08", who: "link", face: "think", dynamic: true, text: "じゃあ、あなたが書いた『{{theme}}』も、もっと強く命令するのは逆効果かもしれない？" },
    },
    {
      kind: "dialogue",
      id: "adv-09",
      scene: "自分への適用",
      camera: "teacher",
      line: { id: "adv-09", who: "teacher", dynamic: true, text: "ええ。あなたはすでに『{{exception}}』という例外を見つけています。次に見る場所はそこです。" },
      nextLabel: "自分の一手を決める",
    },
    {
      kind: "apply",
      id: "apply-self",
      scene: "適用",
      title: "あなたの最初の一手",
      prompt: "『{{theme}}』にUtilizationを使うなら、最初に何をしますか？",
      storeAs: "resource",
      options: [
        { id: "push", label: "できるまで自分へ強く命令する", value: "命令を強める", correct: false, feedback: "漫画で失敗した方法と同じです。力を増やす前に、反応の条件を探します。" },
        { id: "analyze", label: "できない原因を全部分析する", value: "原因を全部分析する", correct: false, feedback: "原因探しだけでは、すでに起きている小さな反応を見落とします。" },
        { id: "observe", label: "『{{exception}}』の違いを観察する", value: "一パーセントだけ違う瞬間を観察する", correct: true, feedback: "正解。そこには無意識がすでに作れている反応の条件があります。" },
      ],
    },
    {
      kind: "dialogue",
      id: "adv-10",
      scene: "解決",
      camera: "link",
      line: { id: "adv-10", who: "link", face: "smile", dynamic: true, text: "『{{theme}}』を根性で直すんじゃない。まず『{{resource}}』。これなら試せそうです。" },
    },
    {
      kind: "dialogue",
      id: "adv-11",
      scene: "解決",
      camera: "teacher",
      line: { id: "adv-11", who: "teacher", face: "smile", dynamic: true, text: "『{{exception}}』を思い出し、呼吸・視線・人・場所のどれが違うか、一つだけ観察してください。" },
    },
    {
      kind: "dialogue",
      id: "adv-12",
      scene: "解決",
      camera: "link",
      line: { id: "adv-12", who: "link", face: "aha", text: "漫画の謎を解いた答えが、そのまま自分を調べる方法になった。やっと話がつながりました。" },
      nextLabel: "事件を解決する",
    },
    {
      kind: "reveal",
      id: "case-closed",
      scene: "CASE CLOSED",
      kicker: "CASE CLOSED",
      title: "無意識は、命令より先に答えている",
      body: "変化を押しつける前に、すでに起きている小さな反応を見つける。それが今回のUtilizationです。",
      evidenceIds: ["direct-command", "vivid-image", "observation-loop"],
      nextLabel: "原理を受け取りに行く",
    },
  ],
});

/** 開発画面・自動生成パイプラインから読める審査結果 */
export const EP1_ADVENTURE_QUALITY = reviewAdventureScenario(EP1_ADVENTURE);
