import { defineAdventureScenario, reviewAdventureScenario } from "./adventure";

export const EP2_ADVENTURE = defineAdventureScenario({
  id: "ep2-case-resistance",
  caseNo: "CASE 02",
  title: "『私は絶対に催眠にかかりません』と言う相手へ、どう催眠をかける？",
  objective: "拒否を説得で消さず、本人が選べる催眠の一言へ変える",
  startLabel: "リンクと事件を追う",
  background: "/learn/adventure/erickson-study-v1.webp",
  teacherSprite: "/learn/adventure/erickson-cutout-v1.webp",
  linkSprite: "/learn/chars/link-neutral.webp",
  evidence: [
    {
      id: "refusal-accepted",
      title: "『かからない』を認めた時",
      summary: "エリクソンは反論せず、かからない選択を認めた",
      detail: "男性が『絶対にかからない』と言うと、エリクソンは説得せず、『では、かからないようにしてください』と答えた。",
      icon: "1",
      image: "/learn/ep2/manga-v1/02.webp",
      imageAlt: "催眠にかからないと言う男性へ、エリクソンがかからないようにしてくださいと答える漫画ページ",
    },
    {
      id: "watching-eyelids",
      title: "まぶたを見張り始めた時",
      summary: "男性は拒否するために、自分のまぶたと呼吸を確かめ始めた",
      detail: "『催眠にかからないために、まぶたが重くなっていないか確かめてください』と言われ、男性は自分の身体を観察し始めた。",
      icon: "2",
      image: "/learn/ep2/manga-v1/03.webp",
      imageAlt: "目を開けた男性が、催眠にかからないと証明するためにまぶたの感覚を確かめる漫画ページ",
    },
    {
      id: "self-choice",
      title: "自分で目を閉じた時",
      summary: "閉じるかどうかは、最後まで男性本人が決めた",
      detail: "男性は変化を自分で見つけ、『目を閉じてもいいですか』と聞いた。エリクソンは『あなたが決めてください』と答えた。",
      icon: "3",
      image: "/learn/ep2/manga-v1/05.webp",
      imageAlt: "男性が自分で目を閉じると決め、椅子へ身体を預ける漫画ページ",
    },
  ],
  nodes: [
    {
      kind: "dialogue",
      id: "ep2-adv-01",
      scene: "拒否された時",
      camera: "link",
      line: { id: "ep2-adv-01", who: "link", face: "think", text: "僕なら『大丈夫、催眠は怖くない』と説得しそうです。でも先生は、説得しなかった。まず何を見ればいいんですか？" },
      nextLabel: "自分の記憶を話す",
    },
    {
      kind: "recall",
      id: "ep2-recall-memory",
      scene: "リンクと記憶を確かめる",
      purpose: "memory",
      title: "男性が『絶対にかからない』と言った直後、先生は何と答えた？",
      prompt: "リンク「正確じゃなくていいよ。漫画で覚えている言葉を、一言で教えて。」",
      placeholder: "覚えている先生の返事を書く",
      helper: "思い出せなければ『まだ分からない』で進めます。",
      storeAs: "ep2FirstMemory",
      skipLabel: "まだ思い出せない",
      skipValue: "先生は男性を説得しなかった",
      replyFallback: "先生は、相手の拒否と争わなかったよね。三つの場面を順に見直そう。",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-02",
      scene: "リンクと記憶を確かめる",
      camera: "link",
      line: { id: "ep2-adv-02", who: "link", face: "think", text: "{{ep2FirstMemoryReply}} 本を開いて、その後に何が起きたか確かめよう。", dynamic: true },
      nextLabel: "本を読み返す",
    },
    {
      kind: "guided-investigation",
      id: "ep2-guided-book",
      scene: "本を読み返す",
      title: "拒否から催眠が始まるまでを、順番に確かめる",
      steps: [
        {
          id: "ep2-guide-accept",
          linkPrompt: "最初は、男性が拒否した直後。先生は『かかりません』を否定したか、認めたかを見よう。",
          actionLabel: "1つ目の場面を本で見る",
          evidenceId: "refusal-accepted",
          linkComment: "先生は『そんなことはない』と反論せず、『かからないように』と言っている。",
          reflectionPrompt: "先生は、男性の『催眠にかからない』という選択をどう扱った？",
          placeholder: "否定した／認めた、のどちらかと理由を書く",
          helper: "先生の返事だけを見て、一つ答えてください。",
          storeAs: "ep2AcceptObservation",
          skipLabel: "まだ分からない",
          skipValue: "かからない選択を認めた",
          replyFallback: "最初に、相手の『かからない』を取り上げなかった点が大事そうだね。",
          linkResponse: "{{ep2AcceptObservationReply}} 次は、男性が自分のまぶたを見始めた理由を見よう。",
          nextLabel: "2つ目へ進む",
        },
        {
          id: "ep2-guide-watch",
          linkPrompt: "男性は、催眠に入りたいからまぶたを見たのか。それとも、別の目的で見たのかを確かめよう。",
          actionLabel: "2つ目の場面を本で見る",
          evidenceId: "watching-eyelids",
          linkComment: "男性は、催眠にかからないと証明するために、まぶたが重くないか見張っている。",
          reflectionPrompt: "男性は、何のために自分のまぶたを確かめ始めた？",
          placeholder: "『催眠に入るため』以外の目的を考える",
          helper: "男性がまだ警戒していることを手がかりにしてください。",
          storeAs: "ep2WatchObservation",
          skipLabel: "まだ分からない",
          skipValue: "催眠にかからないと証明するため",
          replyFallback: "催眠へ協力したつもりではなく、拒否するために観察を始めたんだね。",
          linkResponse: "{{ep2WatchObservationReply}} 最後に、目を閉じると決めたのが誰かを確かめよう。",
          nextLabel: "3つ目へ進む",
        },
        {
          id: "ep2-guide-choice",
          linkPrompt: "最後の場面。先生が目を閉じさせたのか、男性が自分で選んだのかを見よう。",
          actionLabel: "3つ目の場面を本で見る",
          evidenceId: "self-choice",
          linkComment: "男性が『閉じてもいいですか』と聞き、先生は決定を本人へ返している。",
          reflectionPrompt: "目を閉じるかどうかを、最後に決めたのは誰？",
          placeholder: "先生／男性本人、のどちらかを書く",
          helper: "最後の二人の台詞を見て答えてください。",
          storeAs: "ep2ChoiceObservation",
          skipLabel: "まだ分からない",
          skipValue: "男性本人が決めた",
          replyFallback: "最後まで、閉じるかどうかは男性が決めていたね。",
          linkResponse: "{{ep2ChoiceObservationReply}} 三つをつなげて、君の仮説を聞かせて。",
          nextLabel: "三つをつなげる",
        },
      ],
      nextLabel: "リンクに仮説を話す",
    },
    {
      kind: "recall",
      id: "ep2-recall-hypothesis",
      scene: "リンクと仮説を立てる",
      purpose: "hypothesis",
      title: "男性は、なぜ警戒したまま自分の身体を確かめ始めた？",
      prompt: "リンク「説得されてないのに、なぜ観察を始めたんだろう。君の仮説を一言で聞かせて。」",
      placeholder: "三つの場面から考えたことを書く",
      helper: "正解でなくて大丈夫です。『誰が決めたか』も手がかりです。",
      storeAs: "ep2PlayerHypothesis",
      skipLabel: "まだ仮説が浮かばない",
      skipValue: "拒否する選択が残っていたからかもしれない",
      replyFallback: "拒否をやめさせられなかったから、男性は自分で確かめられたのかもしれないね。",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-03",
      scene: "リンクと仮説を立てる",
      camera: "link",
      line: { id: "ep2-adv-03", who: "link", face: "think", text: "{{ep2PlayerHypothesisReply}} 先生。男性が観察を始めたきっかけを、僕たちにも選ばせてください。", dynamic: true },
      nextLabel: "きっかけを選ぶ",
    },
    {
      kind: "deduction",
      id: "ep2-deduce-start",
      scene: "第一推理",
      title: "男性が自分のまぶたを確かめ始めたのは、先生が何をしたから？",
      prompt: "男性が拒否した直後から、まぶたを見張り始めるまでを比べてください。",
      questionBasis: {
        subject: "催眠を拒否した男性",
        before: "『絶対にかからない』と言って腕を組んでいた時",
        asks: "自分のまぶたを確かめ始めたきっかけ",
        goal: "拒否を否定せず、本人の観察を催眠の最初の行動へ変えた一言を特定する",
      },
      options: [
        { id: "force-close", label: "催眠にかかるまで、目を閉じろと命令した", correct: false, feedback: "男性は目を閉じろとは命令されていません。むしろ、閉じなくてよいと言われています。" },
        { id: "accept-watch", label: "『かからなくてよい』と認め、『身体が変化していないか確かめて』と頼んだ", correct: true, feedback: "そうです。拒否をやめさせず、男性自身に身体を確かめてもらいました。" },
        { id: "fake-trance", label: "もう催眠にかかっていると嘘をつき、不安にさせた", correct: false, feedback: "嘘や不安で従わせてはいません。変化を確かめたのは男性本人です。" },
      ],
    },
    {
      kind: "reveal",
      id: "ep2-reveal-case",
      scene: "第一推理成立",
      kicker: "THE REFUSAL BECOMES THE FIRST ACTION",
      title: "拒否をやめさせず、\n催眠の最初の行動へ変えた。",
      body: "『かからない』を否定しなかった。\n男性は拒否するために、自分のまぶたを観察した。\n催眠は、その本人の観察から始まった。",
      nextLabel: "自分の一言で試す",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-04",
      scene: "リンクへの催眠",
      camera: "link",
      line: { id: "ep2-adv-04", who: "link", face: "think", text: "理屈は分かりました。僕で試してもいいです。でも、目を閉じたら操られそうで怖い。目は閉じませんよ。" },
      nextLabel: "リンクへ一言かける",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-05",
      scene: "リンクへの催眠",
      camera: "teacher",
      line: { id: "ep2-adv-05", who: "teacher", text: "{{userName}}。リンクを説得せず、目を閉じない自由を残したまま、催眠を始める一言を選んでください。", dynamic: true },
      nextLabel: "一言を選ぶ",
    },
    {
      kind: "apply",
      id: "ep2-apply-link",
      scene: "リンクへの催眠",
      title: "『目は閉じません』と言うリンクへ、最初に何と言う？",
      prompt: "目的は、目を閉じさせることではありません。リンクが断れる状態を残し、自分の感覚を確かめるところから催眠を始めます。",
      questionBasis: {
        subject: "目を閉じたくないリンク",
        before: "催眠は試してもいいが、目を閉じるのは怖いと言った時",
        asks: "選択権を残して催眠を始める最初の一言",
        goal: "リンクが目を閉じない自由を保ったまま、自分のまぶたへ注意を向けられるようにする",
      },
      storeAs: "openingMove",
      options: [
        { id: "reassure-close", label: "『大丈夫。怖くないから、目を閉じて』", correct: false, value: "怖くないと説得し、目を閉じるよう求めた", feedback: "リンクは『怖いのに分かってもらえない』と身構えます。怖さを否定せず、閉じない選択を残してください。" },
        { id: "keep-open-watch", label: "『目は閉じなくていい。閉じないために、まぶたがどんな感じかだけ確かめて』", correct: true, value: "目を閉じない自由を残し、まぶたの感覚を確かめてもらった", feedback: "リンクは目を閉じなくてよいので、自分のまぶたを安心して確かめられます。" },
        { id: "end-session", label: "『目を閉じないなら、催眠はできません』", correct: false, value: "目を閉じないなら催眠を終えると告げた", feedback: "本人が終わりを望むなら止めます。ただ、リンクは催眠を試すことには同意しています。目を閉じないまま始める方法があります。" },
      ],
    },
    {
      kind: "dialogue",
      id: "ep2-adv-06",
      scene: "リンクへの催眠",
      camera: "link",
      line: { id: "ep2-adv-06", who: "link", face: "think", text: "閉じなくていいなら……目の周りが少し疲れているのは分かります。" },
      nextLabel: "その感覚を確かめる",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-07",
      scene: "リンクへの催眠",
      camera: "teacher",
      line: { id: "ep2-adv-07", who: "teacher", text: "その疲れを変えなくていい。まぶたが重いか軽いか、ただ確かめてください。" },
      nextLabel: "リンクを見る",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-08",
      scene: "リンクへの催眠",
      camera: "link",
      line: { id: "ep2-adv-08", who: "link", face: "aha", text: "少し重くなってきた。でも、まだ閉じません。" },
      nextLabel: "選択を残す",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-09",
      scene: "リンクへの催眠",
      camera: "teacher",
      line: { id: "ep2-adv-09", who: "teacher", text: "そのままで結構です。閉じた方が楽だと、自分で決めるまでは。" },
      nextLabel: "リンクの返事を聞く",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-10",
      scene: "リンクへの催眠",
      camera: "link",
      line: { id: "ep2-adv-10", who: "link", face: "aha", text: "……閉じてもいいですか？" },
      nextLabel: "決定を返す",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-11",
      scene: "リンクへの催眠",
      camera: "teacher",
      line: { id: "ep2-adv-11", who: "teacher", text: "あなたが決めてください。" },
      nextLabel: "リンクを見る",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-12",
      scene: "リンクへの催眠",
      camera: "link",
      line: { id: "ep2-adv-12", who: "link", face: "shy", text: "閉じました。先生の声は聞こえています。怖さはまだ少しあるけど、自分で閉じたから大丈夫です。" },
      nextLabel: "起きたことを考える",
    },
    {
      kind: "recall",
      id: "ep2-recall-link-change",
      scene: "リンクに起きた変化",
      purpose: "reflection",
      title: "リンクは、なぜ自分から目を閉じられたと思う？",
      prompt: "リンク「『閉じて』と説得された時と、閉じないためにまぶたを見た時。何が違ったと思う？」",
      placeholder: "選んだ一言と、リンクの変化をつなげて書く",
      helper: "『誰が決めたか』を手がかりにしてください。",
      storeAs: "ep2LinkChange",
      skipLabel: "まだ分からない",
      skipValue: "閉じるかどうかを自分で決められたから",
      replyFallback: "怖さを消されたのではなく、閉じるかどうかを自分で決められた点が違いそうです。",
    },
    {
      kind: "dialogue",
      id: "ep2-adv-13",
      scene: "リンクに起きた変化",
      camera: "teacher",
      line: { id: "ep2-adv-13", who: "teacher", text: "{{ep2LinkChangeReply}} リンクは、私たちに負けて目を閉じたのではありません。自分の感覚を確かめ、自分で選びました。", dynamic: true },
      nextLabel: "共通点を選ぶ",
    },
    {
      kind: "deduction",
      id: "ep2-deduce-choice",
      scene: "第二推理",
      title: "男性とリンクが目を閉じる直前まで、二人に残されていた選択は？",
      prompt: "二人が目を閉じた直前の会話を比べてください。",
      questionBasis: {
        subject: "漫画の男性とリンク",
        before: "催眠を警戒したまま、自分の身体を確かめ始めた後",
        asks: "二人に最後まで残されていたもの",
        goal: "抵抗のUtilizationが、本人の選択権を奪う操作ではないことを判断する",
      },
      options: [
        { id: "no-refusal", label: "拒否できない空気", correct: false, feedback: "二人とも拒否を続けられ、途中でやめることもできました。" },
        { id: "own-choice", label: "やめるか続けるかを、自分で決められる状態", correct: true, feedback: "その通りです。相手の選択権を残したまま、本人の観察を催眠へつなげました。" },
        { id: "false-belief", label: "すでに催眠にかかったという思い込み", correct: false, feedback: "本人をだましてはいません。起きた変化を本人が確かめ、続けるかを選びました。" },
      ],
    },
    {
      kind: "reveal",
      id: "ep2-reveal-principle",
      scene: "事件解決",
      kicker: "UTILIZATION OF RESISTANCE",
      title: "『したくない』を否定せず、\n本人が選べる暗示へ変える。",
      body: "拒否を説得で消さない。\n何をしたくないのかを聞き、その選択を残す。\n拒否するために本人ができる観察から、催眠を始める。",
      nextLabel: "自分の場面へ使う",
    },
    {
      kind: "apply",
      id: "ep2-apply-own",
      scene: "あなたの一言を作る",
      title: "『{{resistanceScene}}』と言う相手が、断れるまま催眠を試すには何と言う？",
      prompt: "相手を言い負かすのではなく、拒否する自由を残したまま、自分で確かめられる感覚や選択へつなげます。",
      questionBasis: {
        subject: "{{resistanceScene}}と言う相手",
        before: "催眠を試すことには同意しているが、一つのやり方を拒否した時",
        asks: "拒否する選択を残して催眠を始める一言",
        goal: "プレイヤーが相手の拒否を具体的に聞き、本人が選べる催眠の一言へ変える",
      },
      storeAs: "personalMove",
      options: [
        { id: "argue", label: "『そんなことはありません。私を信じてください』", correct: false, value: "相手の拒否へ反論し、信じるよう求めた", feedback: "相手は、自分を守るためにさらに反論したくなります。拒否の内容を認める一言から始めてください。" },
        { id: "accept-and-observe", label: "『それはしなくていい。そのまま、今の感覚が変わらないか自分で確かめてください』", correct: true, value: "拒否を認め、今の感覚を本人に確かめてもらった", feedback: "拒否する自由が残り、相手は自分の意思で今の感覚を観察できます。" },
        { id: "secret-control", label: "何も説明せず、気づかれないように催眠へ誘導する", correct: false, value: "同意を取らず、気づかれないように誘導した", feedback: "同意を隠して進めてはいけません。催眠を試すか、やめるかを本人が選べる状態が必要です。" },
      ],
      freeAnswer: {
        label: "相手へかける一言を、自分で作る",
        placeholder: "例：目は閉じなくていい。そのまま、まぶたの感じだけ確かめてください",
        helper: "『しなくていい』だけで終わらず、本人が選べる観察を一つ入れてください。正解・不正解と理由を返します。",
        storeAs: "customResistanceMove",
        correctCriteria: "相手が拒否した行動を本当にしなくてよいと認め、本人が今できる観察または選択を一つ提案し、続けるかやめるかを本人に残している",
        incorrectCriteria: "拒否を否定する、説得や強制をする、同意を隠す、抽象語だけで本人が何を確かめるか分からない",
      },
    },
    {
      kind: "dialogue",
      id: "ep2-adv-14",
      scene: "事件解決",
      camera: "link",
      line: { id: "ep2-adv-14", who: "link", face: "aha", text: "拒否を消したんじゃない。僕が拒否したまま、自分で確かめ、自分で選べる形に変えたんですね。" },
      nextLabel: "講義で整理する",
    },
  ],
});

export const EP2_ADVENTURE_QUALITY = reviewAdventureScenario(EP2_ADVENTURE);
